language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: LQ/BtHhawaz41O3GNcUzm8MkGl7qeXLDZ7Sv8r/xSIiuXEXoEru6hgm2cpCbnpT5sWzk7fgXsFBbm21CoxVTIUuRz564r0FyqjBmZARZGiF2YONKoxMUDTgDrLmAxtMz9dQl59H4MutF90OUV6lEJveLvodarF1bpNIyptVr70538FdwU2BcfmJnonTXcQpeSqFRKcxRPrYFbWpahw2rhZcKL0DI7omz6yk249tRfMcLEPomEUTV23VOxqqdvtmFfkBC4surxB6PDozy4+x7HLTsGXfVoRN7Qsn4Od6584jo09qCbTO6dUO4dke2KQvKOz8Qrk+/8GE0MbP1oUSD2Lfv/VYOn8LmImVBvKC8b4i8H1vs4RuXeVEv4g4gAd4I161yGJmmA7fp7+0KqtYoCHFA4CTedHgFGSKeiRegvuqFmpxXsw51POpP9X+5dgaTjRSjXCKyCutsjOthu3YkvzmgRFFEEKWQ1cqqOtf0cYZnXo+5i1+/ULnWXQYIFOD/tiNFkcIrWVQvrIv1ZQIMSU7nANu3PE7imdPrEOnrDBNHQ7IIERpDfWi66NZD7ST9msC1utgJ0A2tUHaGULCXjU3urIplqJ2pOV54SGq21k28Lr6/sNF+Fnd5DQiQvor/N55Jn7O/STiw33LOu3EoAWayNHj0iTWDDj8qR81F1Sc=
  app: membersapi
  on:
    repo: junkaiii/myapi
