language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: X4yV9nxCex9w/5lFg7UVF7e9dZXxSgvvAe/vBG9wPEGBDeNBOFefV/lh7omwLhyhyiqbwqP25gyd1J3wbIU7pFDJ0RDMI4VeEPDn9DRSUJrIoE09zl60fFEDCAfC1A6rB6qkSe3K8Hg/qN4cNjsC8e5Qoe3WyGNNkiHZldFDwNB6aBwx0b39uzngmqeYqJuZMSO/0lStYPJps8f6TQL5cZ/OXWdZNvz9QXv3KxTAV0BY7BKk0t3jImEskia6VXu9KaiTkrAErjtnIKht0NS72RT3HfrK+sW5pdRmghfiowdSjJr8vRjrT9TpdEvExv39ReNnW6G+GzNFWMbMy0IRkLi3+Em18M+3OLHfiqm10LO8WN60wgeNv62o71wZvQOC/hLoBNZJF71T2+JmTNRTdkfsmLVQiCI8LJG5f3qv6Bne6+u+WFaqpmOOL36P+qm9Og3UcRFxcVSyylOCGdr5bCIYJ+60/R4gUzgTOiHESoLQOB2frqrjNG98OOkeHZpy4YI9fdy5sDwAjgkWgr2f74a+emM+k3kYvGBCbJxnaBeIUaIVPB4Digz6ubWVX9rGzktcYp47G67x7tF6WawcLANDALQHD3+s3hprIJ/7Afi4qcsSeNJbERtN11pK1pjxcM4D/+O0unC3dmqWfC9IdvKACG3d3zSES7tA+11Q7gY=
  app: membersapi
  on:
    repo: junkaiii/myapi
